### ISSUE TITLE
Invalid factory data when copying from blueprint.

### ISSUE THREAD

**Issue by ZeTBCN** [notnotmelon/factorissimo-2-notnotmelon#153]
**Factorio & Factorissimo version number**
3.77/NA

**Describe the bug**
When I try pasting a blueprint of a factory(probably with crushers 1 from EV refining) from one save to another it returns an error saying incorrect factory data

**To Reproduce**
Steps to reproduce the behavior from a new save:
Start a save
put down a factory
put a building inside a factory
save the factory as a blueprint
reload save/start new one
paste the factory

**Expected behavior**
Factory to be pasted with appropriate building inside

**Screenshots**

https://github.com/user-attachments/assets/9b44244d-3cb6-4a1e-8bf9-8b1cd7d7f9a3

**Additional context**

**Save file & log**

[factorio-current.log](https://github.com/user-attachments/files/18269702/factorio-current.log)

**Comment by notnotmelon** [comment]
Thanks for the report.
After some investigation I have decided I will not fix this. Here is why:

1. Factory interior cloning does not store any data on the blueprint itself. It instead just stores 4 numbers, the positions of a rect to clone from the source factory to the destination factory.
2. I imagine your desired behavior would be to clone factory interiors across save, however due to the way this feature is implemented cross-save blueprinting is impossible.
3. There is no way in the API for me to detect a blueprint that has originated from a different save. Removing or changing the error message here would have the side effect of removing the error in all valid cases that the factory went invalid for some reason.

Unfortunately, due to these technical reasons I cannot resolve this ticket.

**Comment by notnotmelon** [comment]
Good news is I found a crash while investigating, which is now fixed.

**Comment by ZeTBCN** [comment]
> Thanks for the report. After some investigation I have decided I will not fix this. Here is why:
> 
> 1. Factory interior cloning does not store any data on the blueprint itself. It instead just stores 4 numbers, the positions of a rect to clone from the source factory to the destination factory.
> 2. I imagine your desired behavior would be to clone factory interiors across save, however due to the way this feature is implemented cross-save blueprinting is impossible.
> 3. There is no way in the API for me to detect a blueprint that has originated from a different save. Removing or changing the error message here would have the side effect of removing the error in all valid cases that the factory went invalid for some reason.
> 
> Unfortunately, due to these technical reasons I cannot resolve this ticket.

So I cant make a blueprint with a factory and stuff inside of it? I have to make a sperate blueprint for the stuff inside and then paste it into an already placed factory?

**Comment by notnotmelon** [comment]
You can make a blueprint of a factory with stuff inside, however that blueprint just cannot be transferred to another save.
