### ISSUE TITLE
Crash 3.3.1

### ISSUE THREAD

**Issue by Bidovyy** [notnotmelon/factorissimo-2-notnotmelon#42]
Everything works up to version 3.2.1 

When updating to version 3.3 of the mod, a crash occurs and the factorio does not start 

I'll attach the log 

[factorio-current.log](https://github.com/user-attachments/files/17555875/factorio-current.log)

**Comment by PSYcosha** [comment]
Ditto. I have to remove 'factorissimo-2-notnotmelon_3.3.1.zip' from my mods folder just to get the game to start.
My log probably has the same outcome
[factorio-current.log](https://github.com/user-attachments/files/17556334/factorio-current.log)

**Comment by Ergost** [comment]
Crash game whit 3.3.1. Before working well. After delete the mod i can enter the game

**Comment by Daybreaker3** [comment]
I have the same issues with 3.3.1 since updating from 3.2.1 today it is now causing Unexpected error occurred warnings apon lauching 

After removing 3.3.1 and returning back to version 3.2.1 game runs and works.

[factorio-current.log](https://github.com/user-attachments/files/17556518/factorio-current.log)

**Comment by lkshings** [comment]
i had same issues before on 3.3.1 , fixed by updated Factorio to 2.0.12

**Comment by Bidovyy** [comment]
It works, thanks!

**Comment by Daybreaker3** [comment]
Can confirm up and running with no issues currently.
cheers again and thank you for all your effort.
